language: "node_js"
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

before_install:
  - "npm install coveralls"

script:
  - "npm run lint"
  - "npm run test"
  - "cat ./reports/coverage/lcov.info | ./node_modules/.bin/coveralls"
  - "npm run integration"

sudo: false
